version: "3.9"

services:
  patentbot:
    build: .
    container_name: patentbot
    ports:
      - "8000:8000"
    environment:
      - HF_TOKEN=${HF_TOKEN}           # Load from .env
      - MONGO_URI=mongodb://mongo:27017
      - REDIS_URI=redis://redis:6379
    depends_on:
      - mongo
      - redis
    volumes:
      - ./app/parsed_patents:/app/app/parsed_patents
      - ./app/chroma_db_patents:/app/app/chroma_db_patents

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
